// lib/models/question.dart
import 'package:isar/isar.dart';

part 'question.g.dart'; // This will be generated by build_runner

@Collection()
class Question {
  Id? id; // Isar's primary key, auto-incrementing by default if null

  @Index()
  int soruId;
  String soruMetni;

  Question({this.id, required this.soruId, required this.soruMetni});

  factory Question.fromJson(Map<String, dynamic> json) {
    return Question(soruId: json['soru_id'], soruMetni: json['soru_metni']);
  }

  Map<String, dynamic> toJson() {
    return {'soru_id': soruId, 'soru_metni': soruMetni};
  }
}
